FROM node:13

WORKDIR /usr/src/app

COPY . .

RUN npm install

CMD node consumer.js & node consumer.js & node consumer.js & node consumer.js & node consumer.js & node consumer.js & node consumer.js & node consumer.js & node consumer.js & node consumer.js
